output = "./internal/wingedapp/supabase/db/supabasepgmodel"
pkgname = "supabasepgmodel"
no-tests = true

[psql]
dbname  = "postgres"
host    = "localhost"
port    = 5433
user    = "postgres"
pass    = "postgres"
sslmode = "disable"
schema = "public"